// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Domain.Contraception", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Children")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContraceptiveMethod")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HusbandOccupation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LivingStandard")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediaExposure")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WifeAge")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WifeEducation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WifeReligion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WifeWork")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("husbandEducation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Contraceptions");
                });
#pragma warning restore 612, 618
        }
    }
}
