// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200204195841_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Contraception", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Children")
                        .HasColumnType("int");

                    b.Property<int?>("ContraceptiveMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HusbandOccupation")
                        .HasColumnType("int");

                    b.Property<int?>("LivingStandard")
                        .HasColumnType("int");

                    b.Property<int?>("MediaExposure")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WifeAge")
                        .HasColumnType("int");

                    b.Property<int?>("WifeEducation")
                        .HasColumnType("int");

                    b.Property<int?>("WifeReligion")
                        .HasColumnType("int");

                    b.Property<int?>("WifeWork")
                        .HasColumnType("int");

                    b.Property<int?>("husbandEducation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Contraceptions");
                });
#pragma warning restore 612, 618
        }
    }
}
